apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: dev-mongo
data:
  MONGO_INITDB_ROOT_USERNAME: root
  ME_CONFIG_MONGODB_ADMINUSERNAME: root
  ME_CONFIG_MONGODB_URL: mongodb://root:$(MONGO_INITDB_ROOT_PASSWORD)@mongo:27017/
